### ISSUE TITLE
mPDF for Pressbooks

### ISSUE THREAD

**Issue by WhatLibrarian** [pressbooks/docs#32]
The message on the plugin page is:
"This plugin was closed on May 5, 2019 and is no longer available for download."

What is the alternative for this or will mpdf be folded into Pressbooks core?

**Comment by SteelWagstaff** [comment]
Hi @WhatLibrarian -- this was a plugin written by Brad Payne at BCcampus. He's since left his position there and BCcampus has decided to stop actively developing the plugin. It can still be downloaded from GitHub at https://github.com/BCcampus/pressbooks-mpdf and used as long as it still works, but my understanding is that there is no one currently maintaining it, so once it breaks, there's no one around to maintain it. We did not write the plugin and we will not be adopting it/moving it into Pressbooks core, as we use PrinceXML on our hosted networks. We will be updating our installation docs to let users know that the open-source alternative has been abandoned and is now 'use at your own risk.' If you know of someone who is interested in adopting or maintaining the plugin, we'd be happy to put you in contact with Brad or BCcampus colleagues who might be able to give you some assistance/advice in doing so.
